languageCode = "en-us"
title = "Christin & Perry Tea Ceremony"
baseURL = "https://samesense.github.io/tea/"
theme = "hyde"
publishDir = "docs"
name = "Hyde"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.20

[author]
    name = "samesense"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"

[params]
  themeColor = "theme-base-0e"
  description = "Tuesday, Nov 21, 2017 @ noon - The Peninsula Hong Kong"
  disqusShortname = "samesense"